### ISSUE TITLE
Parallel decoding with LexiconDecoder and KenLM using threads

### ISSUE THREAD

**Issue by mrapplexz** [flashlight/text#21]
### Question
Hello! I want to run decoding of different CTC emission matrices in multiple threads, but share a LexiconDecoder object (or just KenLM object) between them to save RAM. What is the proper way to do it?

**Comment by jacobkahn** [comment]
@mrapplexz — sorry for the delay.

Sharing KenLM models across threads has been fine since they're read-only/there's no contention, so you can load them once and pass them to multiple decoders (via `std::shared_ptr`). Creating one `LexiconDecoder` object per thread is required per internal state (Trie state also can't be shared).

Some examples of how we've split this up in Flashlight's [Decode](https://github.com/flashlight/flashlight/blob/main/flashlight/app/asr/Decode.cpp) binary. Hope this helps.
